package cn.com.myorg.bswbuilder.ui.navigator;

import org.eclipse.core.resources.IFolder;
import org.eclipse.jface.viewers.Viewer;
import org.eclipse.jface.viewers.ViewerFilter;

/**
 * Hides the {@code bswmds/} folder from the AUTOSAR Explorer view.
 *
 * <p>Reference V25.10 ships an equivalent filter
 * ({@code cn.com.isoft.pal.filters.BswmdFoldersFilter}, registered as
 * {@code activeByDefault="true"}). The folder contains BSWMD descriptor
 * files (one per module, generated by Update Bswmd) which describe the
 * module's ECUC schema; they are not user-edited and double-clicking them
 * by mistake would open them in the same module-config FormEditor as the
 * real configuration files, causing confusion.
 *
 * <p>The filter is registered as {@code activeByDefault="true"}; users can
 * toggle it off via "Customize View" in the navigator if they need to
 * inspect descriptors directly.
 */
public class BswmdFoldersFilter extends ViewerFilter {

    @Override
    public boolean select(Viewer viewer, Object parentElement, Object element) {
        if (element instanceof IFolder) {
            return !"bswmds".equals(((IFolder) element).getName());
        }
        return true;
    }
}
