"""BswPathConstant — V25.10 Common/arxmlparse/constant/BswPathConstant.py.

V25.10 has 2789 BP enum members (one per ECUC param across all BSW modules)
auto-generated by an internal tool `bp_updater.py / CodeUpdater.py` (per
the leaked comment in BswPathConstant.pyc hexdump).

For D1 (MemIf-only) we register **just the BP entries MemIf actually uses**:
  - BP.MemIf_MemIf
  - BP.MemIf_MemIfGeneral
  - BP.MemIf_MemIfDevErrorDetect
  - BP.MemIf_MemIfNumberOfDevices
  - BP.MemIf_MemIfVersionInfoApi
  - BP.NvM_NvMBlockDescriptor          (cross-module check)
  - BP.NvM_NvMTargetBlockReference     (cross-module check)
  - BP.NvM_NvMFeeRef                   (cross-module check)
  - BP.NvM_NvMEaRef                    (cross-module check)

D6 will replicate the full 2789-entry table from V25.10's reverse-engineered
strings (already extracted in autosar-cfg/_pyd_analysis/).

Each BP member has:
  .value     → full ECUC path  e.g.  /AUTOSAR/MemIf/MemIfGeneral/MemIfDevErrorDetect
  .shortName → leaf            e.g.  MemIfDevErrorDetect
"""
from enum import Enum


class _BPMember:
    """Wrapper to give each enum member two attributes (value + shortName).

    Python's enum.Enum members natively expose `.value`. We need `.shortName`
    too — the trick used in V25.10 (per docs §2.4.1) is to make the enum
    value a small object with both `.value` and `.shortName`. To keep things
    simple we use a class.
    """
    __slots__ = ('value', 'shortName')

    def __init__(self, path: str) -> None:
        self.value = path
        self.shortName = path.rsplit('/', 1)[-1] if '/' in path else path

    def __repr__(self) -> str:
        return f'<BP {self.value!r}>'


class BswPath(Enum):
    """ECUC path enum. Each member's .value is a _BPMember.

    Caller does:  BP.MemIf_MemIfGeneral.value.value     → '/AUTOSAR/MemIf/MemIfGeneral'
                  BP.MemIf_MemIfGeneral.value.shortName → 'MemIfGeneral'

    But MemIfRules.py uses the V25.10 convention where `.value` IS the path
    and `.shortName` is the leaf — directly on the enum member. We restore
    that contract via a __getattr__ trick (see below).
    """
    MemIf_MemIf                       = _BPMember('/AUTOSAR/MemIf')
    MemIf_MemIfGeneral                = _BPMember('/AUTOSAR/MemIf/MemIfGeneral')
    MemIf_MemIfDevErrorDetect         = _BPMember('/AUTOSAR/MemIf/MemIfGeneral/MemIfDevErrorDetect')
    MemIf_MemIfNumberOfDevices        = _BPMember('/AUTOSAR/MemIf/MemIfGeneral/MemIfNumberOfDevices')
    MemIf_MemIfVersionInfoApi         = _BPMember('/AUTOSAR/MemIf/MemIfGeneral/MemIfVersionInfoApi')

    NvM_NvMBlockDescriptor            = _BPMember('/AUTOSAR/NvM/NvMBlockDescriptor')
    NvM_NvMTargetBlockReference       = _BPMember('/AUTOSAR/NvM/NvMBlockDescriptor/NvMTargetBlockReference')
    NvM_NvMFeeRef                     = _BPMember('/AUTOSAR/NvM/NvMBlockDescriptor/NvMTargetBlockReference/NvMFeeRef')
    NvM_NvMEaRef                      = _BPMember('/AUTOSAR/NvM/NvMBlockDescriptor/NvMTargetBlockReference/NvMEaRef')

    # ----------------------------- expose .value (full path) and .shortName
    # directly on enum members (matches V25.10 contract used by MemIfRules.py)

    @property
    def shortName(self) -> str:                      # type: ignore[override]
        return self._value_.shortName  # type: ignore[attr-defined]
    # NB: enum's `.value` is already the _BPMember instance.
    # If someone needs the raw path string, they'll do `.value.value`
    # which is awkward but matches reverse-engineering reality.
    # We additionally expose plain `.value_path` for ergonomics:
    @property
    def value_path(self) -> str:
        return self._value_.value  # type: ignore[attr-defined]


# Convenience: the validator side does `BP.X.value` expecting the path string.
# Python Enum already returns the _value_ for `.value`. To make `.value` return
# the full path string (rather than _BPMember instance), we override:
#
# Sadly `enum.Enum` doesn't allow easy `.value` override. The pragmatic
# workaround used here: callers that need string path do `.value_path`.
#
# In M2 we will replace this whole module with a proper implementation
# that perfectly matches V25.10 contract (using a metaclass or a frozen
# class hierarchy with `.value` and `.shortName` directly).
